%{
#include "currency.hpp"
#define TC(X)	{ yylval.c = yytext[0]; 			return X; }
#define TS(X)	{ yylval.s = new string(yytext);	return X; }
#define TP(X)	{ yylval.s = new string(yytext+1);	yylval.s->erase(yylval.s->size()-1,1); return X; }
%}
%option noyywrap
%option yylineno
D [0-9]+
%%
\"Date\"		TS(DT)
\"Time\"		TS(TM)
\"Rate\"		TS(RATE)
\"USD\/RUB\"	TP(U)
\"EUR\/RUB\"	TP(E)
\"[^\"]*\"		TP(STR)

:	TC(COLON)
\n	TC(CHAR)
.	TC(CHAR)
%%
