%{
#include "weather.hpp"
#define TC(X)	{ yylval.c = yytext[0]; 			return X; }
#define TS(X)	{ yylval.s = new string(yytext); 	return X; }
%}
%option noyywrap
%option yylineno
S	[\+\-]{0,1}
D	[0-9]+
%%
{S}{D}(\.{D})?		TS(NUM)
\"dt_txt\"			TS(DT)
\"temp\"			TS(TEMP)
\"humidity\"		TS(HUM)
\"pressure\"		TS(PRESS)
\"rain\":\{[^\}]*\}	TS(RAIN)
\"snow\":\{[^\}]*\}	TS(SNOW)
\"[^\"]*\"			TS(STR)
:					TC(COLON)
\n					TC(CHAR)
.					TC(CHAR)
%%
